// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xun_go
    (
        init => init
        certifySkill => certify_skill
        getUserSkills => get_user_skills
        revokeCertificate => revoke_certificate
        getCertificates => certificates
        userCertificates => user_certificates
        certificateCounter => certificate_counter
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
